### ISSUE TITLE
Umblera rakefile dump task error

### ISSUE THREAD

**Issue by CucumisSativus** [dry-rb/dry-web-roda#3]
Hey guys,

while using `rake db:migrate` task (which uses `dump` rake task) I encountered the following error:

```
pg_dump: invalid option -- i
Try "pg_dump --help" for more information.
```

After removing `-i` option from https://github.com/dry-rb/dry-web-roda/blob/master/lib/dry/web/roda/skeletons/umbrella/Rakefile.tt#L40 everything works as expected. Not sure if that option was opened on purpose or its just a bug.

Postgres Version:
postgres (PostgreSQL) 9.5.2 on MacOSx installed via brew

**Comment by timriley** [comment]
Thanks for the report! I just fixed this in https://github.com/dry-rb/dry-web-roda/commit/63ecc2ea7eb645e7a0a533d8d26bf0bdd59f2875 and will release a new gem version today.
