### ISSUE TITLE
Remove rack_csrf dependency

### ISSUE THREAD

**Issue by musaffa** [dry-rb/dry-web-roda#63]
`dry-web-roda`'s dry_view roda plugin has a dependency on `rack_csrf` gem. When using `dry-web-roda` as an API server, csrf is not needed. Better if this csrf dependency is removed.

**Comment by timriley** [comment]
Thanks @musaffa — I'll move this into the generated `Dry::Web::Roda::Application` subclasses instead. I'll try and do this sometime later this week.

**Comment by musaffa** [comment]
An API server may need `dry_view` roda plugin as well e.g. for mailing purposes. It just doesn't need csrf and flash as view context options.

**Comment by AMHOL** [comment]
API server could also use dry-view with jbuilder or something.
