### ISSUE TITLE
Generator generate misaligned gemfile

### ISSUE THREAD

**Issue by ernepriv** [dry-rb/dry-web-roda#70]
I have installed dry-web-roda (0.9.1)
when i run `dry-web-roda new new_project`
it generates gem file with an older version of some gems
```
gem "dry-web", "~> 0.7"
gem "dry-web-roda", "~> 0.7"
```

**Comment by v-kolesnikov** [comment]
Hi, @ernepriv !
What are happening when you run `bundle install`?
I can suppose that it installs latest available gem versions (0.9.1), right? So, it is not a bug as I see.

**Comment by ernepriv** [comment]
No, because in the gemfile template used by dry-web-roda to build a new project, it uses the `"~> 0.7"` to force this version, so when i run `bundle install` it still remains 0.7. 
I think that the string `gem "dry-web", "~> 0.7"` must be updated in the gemfile template of the gem.

**Comment by v-kolesnikov** [comment]
It will solve problem in any case, of course. Though I tried to replay this scenario and have got that result - bundler installed dry-web-roda 0.9.1 for me. 🤔

**Comment by alejandrobabio** [comment]
@ernepriv I guess you have more than one version of dry-web-roda installed in your system, so you can verify it with `$ gem list dry-web-roda` if I'm right, you should uninstall the old version(s). Remove the `new_project` folder and start again.

**Comment by ernepriv** [comment]
I have only the 0.9.1 version installed, but what i mean is that the file located here as template:

 https://github.com/dry-rb/dry-web-roda/blob/master/lib/dry/web/roda/templates/Gemfile
```
source "https://rubygems.org"

gem "rake"

# Web framework
gem "dry-system", "~> 0.8"
gem "dry-web", "~> 0.7"
gem "dry-web-roda", "~> 0.7"
gem "puma"
gem "rack_csrf"

gem "rack", ">= 2.0"
gem "shotgun", ">= 0.9.2"

# Database persistence
gem "pg"
gem "rom", "~> 4.0"
gem "rom-sql", "~> 2.1"

# Application dependencies
gem "dry-matcher", "~> 0.6.0"
gem "dry-monads", "~> 0.3"
gem "dry-struct", "~> 0.3"
gem "dry-transaction", "~> 0.10"
gem "dry-types", "~> 0.12"
gem "dry-validation", "~> 0.11"
gem "dry-view", "~> 0.4"
gem "slim"

group :development, :test do
  gem "pry-byebug", platform: :mri
end

group :test do
  gem "capybara"
  gem "capybara-screenshot"
  gem "database_cleaner"
  gem "poltergeist"
  gem "rspec"
  gem "rom-factory", "~> 0.5"
end
```
uses an old version of some gems, i know that i can update it manually, but it could be nice to update that template!

**Comment by timriley** [comment]
Thanks for finding this oversight :) I’ll be able to fix this next week, and even faster if someone submits a PR ;)

**Comment by alejandrobabio** [comment]
@ernepriv I read again your first post for this issue.

You said that the `Gemfile` of your generated project `my_project` is wrong because it has the lines:

```ruby
gem "dry-web", "~> 0.7"
gem "dry-web-roda", "~> 0.7"
```
As I understand you, you expect to see something different in the version number. Right?

Well. If you do:

```shell
$ cd my_project
$ bundle install
$ bundle show dry-web-roda
```

You will see that you are using the right version of the gem.

Actually, `gem "dry-web-roda", "~> 0.7"` resolves to last version `0.x.y`, right now `0.9.1`.
