### ISSUE TITLE
Root returns 404 on fresh install

### ISSUE THREAD

**Issue by victormartins** [dry-rb/dry-web-roda#80]
Hey guys, I'm having trouble reaching the Welcome page after a fresh install. 
I don't know If I'm missing any step so I made a video showing what I'm doing.
Thank you.

![dry-web-roda](https://user-images.githubusercontent.com/178493/36091900-5a968be8-0fdd-11e8-9e93-d9c857528faf.gif)

**Comment by GustavoCaso** [comment]
This PR will solve that issue https://github.com/dry-rb/dry-web-roda/pull/81

**Comment by GustavoCaso** [comment]
@victormartins I will try to have a release later today so you can update :)

**Comment by victormartins** [comment]
@GustavoCaso Thank you :)

**Comment by timriley** [comment]
@victormartins Thanks for filing the issue! We've just released 0.10.0 today which should fix it. Please have another go :)

**Comment by victormartins** [comment]
@timriley @GustavoCaso 
Just saw **Welcome to dry-web-roda!**
Happy days :) Thank you!
I will make my current pet project using this framework. 
My idea is to have a React UI frontend that uses a JSON API provided by Dry-Web-Roda.
