### ISSUE TITLE
dry-web-roda app initialisation issues

### ISSUE THREAD

**Issue by mlk5060** [dry-rb/dry-web-roda#98]
After using the following procedure to generate and start a new application, I received some errors that were difficult to diagnose and fix for newcomers: 

1. `dry-web-roda new APP_NAME` 
2. `rake db:create`
3. `rerun -- rackup --port 4000 config.ru`

The first issue was that the event `sql` had not been registered. After some digging, and with help from @solnic on Zulip, I discovered that the issue lay in the `system/boot/monitor.rb` file. After fixing this, I received a validation error saying that a password was not supplied when initialising the PostgreSQL connection. A fix for this is to specify the username and password as part of the `DATABASE_URL` variable in the top-level `.env` created when `dry-web-roda new APP_NAME` is run. Alternatively, a user could pre-pend the variable declaration to step 3 above. Either way, I think this set-up step could be better explained in the README for first time use?

As discussed with @solnic yesterday, I will make a pull-request for this issue with some fixes and submit for review. Thanks again for all your hard work on this project!

**Comment by solnic** [comment]
this was fixed via #99
